<?php
/*
    Copyright 2020 FWBer.com

    This file is part of FWBer.

    FWBer is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    FWBer is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero Public License for more details.

    You should have received a copy of the GNU Affero Public License
    along with FWBer.  If not, see <https://www.gnu.org/licenses/>.
*/
?>

			<option value="United States" <?php if($profileDone==0)echo 'selected="selected"'; ?>>United States</option>
			
			<option value="Afghanistan"                                 			<?php if($profileDone==1&&$country=="Afghanistan"                                 			)echo 'selected="selected"'; ?>>Afghanistan                                 	</option>
			<option value="Aland Islands"                               			<?php if($profileDone==1&&$country=="Aland Islands"                               			)echo 'selected="selected"'; ?>>Aland Islands                               	</option>
			<option value="Albania"                                     			<?php if($profileDone==1&&$country=="Albania"                                     			)echo 'selected="selected"'; ?>>Albania                                     	</option>
			<option value="Algeria"                                     			<?php if($profileDone==1&&$country=="Algeria"                                     			)echo 'selected="selected"'; ?>>Algeria                                     	</option>
			<option value="American Samoa"                              			<?php if($profileDone==1&&$country=="American Samoa"                              			)echo 'selected="selected"'; ?>>American Samoa                              	</option>
			<option value="Andorra"                                     			<?php if($profileDone==1&&$country=="Andorra"                                     			)echo 'selected="selected"'; ?>>Andorra                                     	</option>
			<option value="Angola"                                      			<?php if($profileDone==1&&$country=="Angola"                                      			)echo 'selected="selected"'; ?>>Angola                                      	</option>
			<option value="Anguilla"                                    			<?php if($profileDone==1&&$country=="Anguilla"                                    			)echo 'selected="selected"'; ?>>Anguilla                                    	</option>
			<option value="Antarctica"                                  			<?php if($profileDone==1&&$country=="Antarctica"                                  			)echo 'selected="selected"'; ?>>Antarctica                                  	</option>
			<option value="Antigua and Barbuda"                         			<?php if($profileDone==1&&$country=="Antigua and Barbuda"                         			)echo 'selected="selected"'; ?>>Antigua and Barbuda                         	</option>
			<option value="Argentina"                                   			<?php if($profileDone==1&&$country=="Argentina"                                   			)echo 'selected="selected"'; ?>>Argentina                                   	</option>
			<option value="Armenia"                                     			<?php if($profileDone==1&&$country=="Armenia"                                     			)echo 'selected="selected"'; ?>>Armenia                                     	</option>
			<option value="Aruba"                                       			<?php if($profileDone==1&&$country=="Aruba"                                       			)echo 'selected="selected"'; ?>>Aruba                                       	</option>
			<option value="Australia"                                   			<?php if($profileDone==1&&$country=="Australia"                                   			)echo 'selected="selected"'; ?>>Australia                                   	</option>
			<option value="Austria"                                     			<?php if($profileDone==1&&$country=="Austria"                                     			)echo 'selected="selected"'; ?>>Austria                                     	</option>
			<option value="Azerbaijan"                                  			<?php if($profileDone==1&&$country=="Azerbaijan"                                  			)echo 'selected="selected"'; ?>>Azerbaijan                                  	</option>
			<option value="Bahamas"                                     			<?php if($profileDone==1&&$country=="Bahamas"                                     			)echo 'selected="selected"'; ?>>Bahamas                                     	</option>
			<option value="Bahrain"                                     			<?php if($profileDone==1&&$country=="Bahrain"                                     			)echo 'selected="selected"'; ?>>Bahrain                                     	</option>
			<option value="Bangladesh"                                  			<?php if($profileDone==1&&$country=="Bangladesh"                                  			)echo 'selected="selected"'; ?>>Bangladesh                                  	</option>
			<option value="Barbados"                                    			<?php if($profileDone==1&&$country=="Barbados"                                    			)echo 'selected="selected"'; ?>>Barbados                                    	</option>
			<option value="Belarus"                                     			<?php if($profileDone==1&&$country=="Belarus"                                     			)echo 'selected="selected"'; ?>>Belarus                                     	</option>
			<option value="Belgium"                                     			<?php if($profileDone==1&&$country=="Belgium"                                     			)echo 'selected="selected"'; ?>>Belgium                                     	</option>
			<option value="Belize"                                      			<?php if($profileDone==1&&$country=="Belize"                                      			)echo 'selected="selected"'; ?>>Belize                                      	</option>
			<option value="Benin"                                       			<?php if($profileDone==1&&$country=="Benin"                                       			)echo 'selected="selected"'; ?>>Benin                                       	</option>
			<option value="Bermuda"                                     			<?php if($profileDone==1&&$country=="Bermuda"                                     			)echo 'selected="selected"'; ?>>Bermuda                                     	</option>
			<option value="Bhutan"                                      			<?php if($profileDone==1&&$country=="Bhutan"                                      			)echo 'selected="selected"'; ?>>Bhutan                                      	</option>
			<option value="Bolivia"                                     			<?php if($profileDone==1&&$country=="Bolivia"                                     			)echo 'selected="selected"'; ?>>Bolivia                                     	</option>
			<option value="Bonaire- Saint Eustatius and Saba"          		        <?php if($profileDone==1&&$country=="Bonaire- Saint Eustatius and Saba"          			)echo 'selected="selected"'; ?>>Bonaire- Saint Eustatius and Saba           	</option>
			<option value="Bosnia and Herzegovina"                      			<?php if($profileDone==1&&$country=="Bosnia and Herzegovina"                      			)echo 'selected="selected"'; ?>>Bosnia and Herzegovina                      	</option>
			<option value="Botswana"                                    			<?php if($profileDone==1&&$country=="Botswana"                                    			)echo 'selected="selected"'; ?>>Botswana                                    	</option>
			<option value="Bouvet Island"                               			<?php if($profileDone==1&&$country=="Bouvet Island"                               			)echo 'selected="selected"'; ?>>Bouvet Island                               	</option>
			<option value="Brazil"                                      			<?php if($profileDone==1&&$country=="Brazil"                                      			)echo 'selected="selected"'; ?>>Brazil                                      	</option>
			<option value="British Indian Ocean Territory"              		    <?php if($profileDone==1&&$country=="British Indian Ocean Territory"              			)echo 'selected="selected"'; ?>>British Indian Ocean Territory              	</option>
			<option value="British Virgin Islands"                      			<?php if($profileDone==1&&$country=="British Virgin Islands"                      			)echo 'selected="selected"'; ?>>British Virgin Islands                      	</option>
			<option value="Brunei"                                      			<?php if($profileDone==1&&$country=="Brunei"                                      			)echo 'selected="selected"'; ?>>Brunei                                      	</option>
			<option value="Bulgaria"                                    			<?php if($profileDone==1&&$country=="Bulgaria"                                    			)echo 'selected="selected"'; ?>>Bulgaria                                    	</option>
			<option value="Burkina Faso"                                			<?php if($profileDone==1&&$country=="Burkina Faso"                                			)echo 'selected="selected"'; ?>>Burkina Faso                                	</option>
			<option value="Burundi"                                     			<?php if($profileDone==1&&$country=="Burundi"                                     			)echo 'selected="selected"'; ?>>Burundi                                     	</option>
			<option value="Cambodia"                                    			<?php if($profileDone==1&&$country=="Cambodia"                                    			)echo 'selected="selected"'; ?>>Cambodia                                    	</option>
			<option value="Cameroon"                                    			<?php if($profileDone==1&&$country=="Cameroon"                                    			)echo 'selected="selected"'; ?>>Cameroon                                    	</option>
			<option value="Canada"                                      			<?php if($profileDone==1&&$country=="Canada"                                      			)echo 'selected="selected"'; ?>>Canada                                      	</option>
			<option value="Cape Verde"                                  			<?php if($profileDone==1&&$country=="Cape Verde"                                  			)echo 'selected="selected"'; ?>>Cape Verde                                  	</option>
			<option value="Cayman Islands"                              			<?php if($profileDone==1&&$country=="Cayman Islands"                              			)echo 'selected="selected"'; ?>>Cayman Islands                              	</option>
			<option value="Central African Republic"                    		    <?php if($profileDone==1&&$country=="Central African Republic"                    			)echo 'selected="selected"'; ?>>Central African Republic                    	</option>
			<option value="Chad"                                        			<?php if($profileDone==1&&$country=="Chad"                                        			)echo 'selected="selected"'; ?>>Chad                                        	</option>
			<option value="Chile"                                       			<?php if($profileDone==1&&$country=="Chile"                                       			)echo 'selected="selected"'; ?>>Chile                                       	</option>
			<option value="China"                                       			<?php if($profileDone==1&&$country=="China"                                       			)echo 'selected="selected"'; ?>>China                                       	</option>
			<option value="Christmas Island"                            			<?php if($profileDone==1&&$country=="Christmas Island"                            			)echo 'selected="selected"'; ?>>Christmas Island                            	</option>
			<option value="Cocos Islands"                               			<?php if($profileDone==1&&$country=="Cocos Islands"                               			)echo 'selected="selected"'; ?>>Cocos Islands                               	</option>
			<option value="Colombia"                                    			<?php if($profileDone==1&&$country=="Colombia"                                    			)echo 'selected="selected"'; ?>>Colombia                                    	</option>
			<option value="Comoros"                                     			<?php if($profileDone==1&&$country=="Comoros"                                     			)echo 'selected="selected"'; ?>>Comoros                                     	</option>
			<option value="Cook Islands"                                			<?php if($profileDone==1&&$country=="Cook Islands"                                			)echo 'selected="selected"'; ?>>Cook Islands                                	</option>
			<option value="Costa Rica"                                  			<?php if($profileDone==1&&$country=="Costa Rica"                                  			)echo 'selected="selected"'; ?>>Costa Rica                                  	</option>
			<option value="Croatia"                                     			<?php if($profileDone==1&&$country=="Croatia"                                     			)echo 'selected="selected"'; ?>>Croatia                                     	</option>
			<option value="Cuba"                                        			<?php if($profileDone==1&&$country=="Cuba"                                        			)echo 'selected="selected"'; ?>>Cuba                                        	</option>
			<option value="Curacao"                                     			<?php if($profileDone==1&&$country=="Curacao"                                     			)echo 'selected="selected"'; ?>>Curacao                                     	</option>
			<option value="Cyprus"                                      			<?php if($profileDone==1&&$country=="Cyprus"                                      			)echo 'selected="selected"'; ?>>Cyprus                                      	</option>
			<option value="Czech Republic"                              			<?php if($profileDone==1&&$country=="Czech Republic"                              			)echo 'selected="selected"'; ?>>Czech Republic                              	</option>
			<option value="Democratic Republic of the Congo"           		        <?php if($profileDone==1&&$country=="Democratic Republic of the Congo"           			)echo 'selected="selected"'; ?>>Democratic Republic of the Congo            	</option>
			<option value="Denmark"                                     			<?php if($profileDone==1&&$country=="Denmark"                                     			)echo 'selected="selected"'; ?>>Denmark                                     	</option>
			<option value="Djibouti"                                    			<?php if($profileDone==1&&$country=="Djibouti"                                    			)echo 'selected="selected"'; ?>>Djibouti                                    	</option>
			<option value="Dominica"                                    			<?php if($profileDone==1&&$country=="Dominica"                                    			)echo 'selected="selected"'; ?>>Dominica                                    	</option>
			<option value="Dominican Republic"                          			<?php if($profileDone==1&&$country=="Dominican Republic"                          			)echo 'selected="selected"'; ?>>Dominican Republic                          	</option>
			<option value="East Timor"                                  			<?php if($profileDone==1&&$country=="East Timor"                                  			)echo 'selected="selected"'; ?>>East Timor                                  	</option>
			<option value="Ecuador"                                     			<?php if($profileDone==1&&$country=="Ecuador"                                     			)echo 'selected="selected"'; ?>>Ecuador                                     	</option>
			<option value="Egypt"                                       			<?php if($profileDone==1&&$country=="Egypt"                                       			)echo 'selected="selected"'; ?>>Egypt                                       	</option>
			<option value="El Salvador"                                 			<?php if($profileDone==1&&$country=="El Salvador"                                 			)echo 'selected="selected"'; ?>>El Salvador                                 	</option>
			<option value="Equatorial Guinea"                           			<?php if($profileDone==1&&$country=="Equatorial Guinea"                           			)echo 'selected="selected"'; ?>>Equatorial Guinea                           	</option>
			<option value="Eritrea"                                     			<?php if($profileDone==1&&$country=="Eritrea"                                     			)echo 'selected="selected"'; ?>>Eritrea                                     	</option>
			<option value="Estonia"                                     			<?php if($profileDone==1&&$country=="Estonia"                                     			)echo 'selected="selected"'; ?>>Estonia                                     	</option>
			<option value="Ethiopia"                                    			<?php if($profileDone==1&&$country=="Ethiopia"                                    			)echo 'selected="selected"'; ?>>Ethiopia                                    	</option>
			<option value="Falkland Islands"                            			<?php if($profileDone==1&&$country=="Falkland Islands"                            			)echo 'selected="selected"'; ?>>Falkland Islands                            	</option>
			<option value="Faroe Islands"                               			<?php if($profileDone==1&&$country=="Faroe Islands"                               			)echo 'selected="selected"'; ?>>Faroe Islands                               	</option>
			<option value="Fiji"                                        			<?php if($profileDone==1&&$country=="Fiji"                                        			)echo 'selected="selected"'; ?>>Fiji                                        	</option>
			<option value="Finland"                                     			<?php if($profileDone==1&&$country=="Finland"                                     			)echo 'selected="selected"'; ?>>Finland                                     	</option>
			<option value="France"                                      			<?php if($profileDone==1&&$country=="France"                                      			)echo 'selected="selected"'; ?>>France                                      	</option>
			<option value="French Guiana"                               			<?php if($profileDone==1&&$country=="French Guiana"                               			)echo 'selected="selected"'; ?>>French Guiana                               	</option>
			<option value="French Polynesia"                            			<?php if($profileDone==1&&$country=="French Polynesia"                            			)echo 'selected="selected"'; ?>>French Polynesia                            	</option>
			<option value="French Southern Territories"                 		    <?php if($profileDone==1&&$country=="French Southern Territories"                 			)echo 'selected="selected"'; ?>>French Southern Territories                 	</option>
			<option value="Gabon"                                       			<?php if($profileDone==1&&$country=="Gabon"                                       			)echo 'selected="selected"'; ?>>Gabon                                       	</option>
			<option value="Gambia"                                      			<?php if($profileDone==1&&$country=="Gambia"                                      			)echo 'selected="selected"'; ?>>Gambia                                      	</option>
			<option value="Georgia"                                     			<?php if($profileDone==1&&$country=="Georgia"                                     			)echo 'selected="selected"'; ?>>Georgia                                     	</option>
			<option value="Germany"                                     			<?php if($profileDone==1&&$country=="Germany"                                     			)echo 'selected="selected"'; ?>>Germany                                     	</option>
			<option value="Ghana"                                       			<?php if($profileDone==1&&$country=="Ghana"                                       			)echo 'selected="selected"'; ?>>Ghana                                       	</option>
			<option value="Gibraltar"                                   			<?php if($profileDone==1&&$country=="Gibraltar"                                   			)echo 'selected="selected"'; ?>>Gibraltar                                   	</option>
			<option value="Greece"                                      			<?php if($profileDone==1&&$country=="Greece"                                      			)echo 'selected="selected"'; ?>>Greece                                      	</option>
			<option value="Greenland"                                   			<?php if($profileDone==1&&$country=="Greenland"                                   			)echo 'selected="selected"'; ?>>Greenland                                   	</option>
			<option value="Grenada"                                     			<?php if($profileDone==1&&$country=="Grenada"                                     			)echo 'selected="selected"'; ?>>Grenada                                     	</option>
			<option value="Guadeloupe"                                  			<?php if($profileDone==1&&$country=="Guadeloupe"                                  			)echo 'selected="selected"'; ?>>Guadeloupe                                  	</option>
			<option value="Guam"                                        			<?php if($profileDone==1&&$country=="Guam"                                        			)echo 'selected="selected"'; ?>>Guam                                        	</option>
			<option value="Guatemala"                                   			<?php if($profileDone==1&&$country=="Guatemala"                                   			)echo 'selected="selected"'; ?>>Guatemala                                   	</option>
			<option value="Guernsey"                                    			<?php if($profileDone==1&&$country=="Guernsey"                                    			)echo 'selected="selected"'; ?>>Guernsey                                    	</option>
			<option value="Guinea"                                      			<?php if($profileDone==1&&$country=="Guinea"                                      			)echo 'selected="selected"'; ?>>Guinea                                      	</option>
			<option value="Guinea-Bissau"                               			<?php if($profileDone==1&&$country=="Guinea-Bissau"                               			)echo 'selected="selected"'; ?>>Guinea-Bissau                               	</option>
			<option value="Guyana"                                      			<?php if($profileDone==1&&$country=="Guyana"                                      			)echo 'selected="selected"'; ?>>Guyana                                      	</option>
			<option value="Haiti"                                       			<?php if($profileDone==1&&$country=="Haiti"                                       			)echo 'selected="selected"'; ?>>Haiti                                       	</option>
			<option value="Heard Island and McDonald Islands"          		        <?php if($profileDone==1&&$country=="Heard Island and McDonald Islands"          			)echo 'selected="selected"'; ?>>Heard Island and McDonald Islands           	</option>
			<option value="Honduras"                                    			<?php if($profileDone==1&&$country=="Honduras"                                    			)echo 'selected="selected"'; ?>>Honduras                                    	</option>
			<option value="Hong Kong"                                   			<?php if($profileDone==1&&$country=="Hong Kong"                                   			)echo 'selected="selected"'; ?>>Hong Kong                                   	</option>
			<option value="Hungary"                                     			<?php if($profileDone==1&&$country=="Hungary"                                     			)echo 'selected="selected"'; ?>>Hungary                                     	</option>
			<option value="Iceland"                                     			<?php if($profileDone==1&&$country=="Iceland"                                     			)echo 'selected="selected"'; ?>>Iceland                                     	</option>
			<option value="India"                                       			<?php if($profileDone==1&&$country=="India"                                       			)echo 'selected="selected"'; ?>>India                                       	</option>
			<option value="Indonesia"                                   			<?php if($profileDone==1&&$country=="Indonesia"                                   			)echo 'selected="selected"'; ?>>Indonesia                                   	</option>
			<option value="Iran"                                        			<?php if($profileDone==1&&$country=="Iran"                                        			)echo 'selected="selected"'; ?>>Iran                                        	</option>
			<option value="Iraq"                                        			<?php if($profileDone==1&&$country=="Iraq"                                        			)echo 'selected="selected"'; ?>>Iraq                                        	</option>
			<option value="Ireland"                                     			<?php if($profileDone==1&&$country=="Ireland"                                     			)echo 'selected="selected"'; ?>>Ireland                                     	</option>
			<option value="Isle of Man"                                 			<?php if($profileDone==1&&$country=="Isle of Man"                                 			)echo 'selected="selected"'; ?>>Isle of Man                                 	</option>
			<option value="Israel"                                      			<?php if($profileDone==1&&$country=="Israel"                                      			)echo 'selected="selected"'; ?>>Israel                                      	</option>
			<option value="Italy"                                       			<?php if($profileDone==1&&$country=="Italy"                                       			)echo 'selected="selected"'; ?>>Italy                                       	</option>
			<option value="Ivory Coast"                                 			<?php if($profileDone==1&&$country=="Ivory Coast"                                 			)echo 'selected="selected"'; ?>>Ivory Coast                                 	</option>
			<option value="Jamaica"                                     			<?php if($profileDone==1&&$country=="Jamaica"                                     			)echo 'selected="selected"'; ?>>Jamaica                                     	</option>
			<option value="Japan"                                       			<?php if($profileDone==1&&$country=="Japan"                                       			)echo 'selected="selected"'; ?>>Japan                                       	</option>
			<option value="Jersey"                                      			<?php if($profileDone==1&&$country=="Jersey"                                      			)echo 'selected="selected"'; ?>>Jersey                                      	</option>
			<option value="Jordan"                                      			<?php if($profileDone==1&&$country=="Jordan"                                      			)echo 'selected="selected"'; ?>>Jordan                                      	</option>
			<option value="Kazakhstan"                                  			<?php if($profileDone==1&&$country=="Kazakhstan"                                  			)echo 'selected="selected"'; ?>>Kazakhstan                                  	</option>
			<option value="Kenya"                                       			<?php if($profileDone==1&&$country=="Kenya"                                       			)echo 'selected="selected"'; ?>>Kenya                                       	</option>
			<option value="Kiribati"                                    			<?php if($profileDone==1&&$country=="Kiribati"                                    			)echo 'selected="selected"'; ?>>Kiribati                                    	</option>
			<option value="Kosovo"                                      			<?php if($profileDone==1&&$country=="Kosovo"                                      			)echo 'selected="selected"'; ?>>Kosovo                                      	</option>
			<option value="Kuwait"                                      			<?php if($profileDone==1&&$country=="Kuwait"                                      			)echo 'selected="selected"'; ?>>Kuwait                                      	</option>
			<option value="Kyrgyzstan"                                  			<?php if($profileDone==1&&$country=="Kyrgyzstan"                                  			)echo 'selected="selected"'; ?>>Kyrgyzstan                                  	</option>
			<option value="Laos"                                        			<?php if($profileDone==1&&$country=="Laos"                                        			)echo 'selected="selected"'; ?>>Laos                                        	</option>
			<option value="Latvia"                                      			<?php if($profileDone==1&&$country=="Latvia"                                      			)echo 'selected="selected"'; ?>>Latvia                                      	</option>
			<option value="Lebanon"                                     			<?php if($profileDone==1&&$country=="Lebanon"                                     			)echo 'selected="selected"'; ?>>Lebanon                                     	</option>
			<option value="Lesotho"                                     			<?php if($profileDone==1&&$country=="Lesotho"                                     			)echo 'selected="selected"'; ?>>Lesotho                                     	</option>
			<option value="Liberia"                                     			<?php if($profileDone==1&&$country=="Liberia"                                     			)echo 'selected="selected"'; ?>>Liberia                                     	</option>
			<option value="Libya"                                       			<?php if($profileDone==1&&$country=="Libya"                                       			)echo 'selected="selected"'; ?>>Libya                                       	</option>
			<option value="Liechtenstein"                               			<?php if($profileDone==1&&$country=="Liechtenstein"                               			)echo 'selected="selected"'; ?>>Liechtenstein                               	</option>
			<option value="Lithuania"                                   			<?php if($profileDone==1&&$country=="Lithuania"                                   			)echo 'selected="selected"'; ?>>Lithuania                                   	</option>
			<option value="Luxembourg"                                  			<?php if($profileDone==1&&$country=="Luxembourg"                                  			)echo 'selected="selected"'; ?>>Luxembourg                                  	</option>
			<option value="Macao"                                       			<?php if($profileDone==1&&$country=="Macao"                                       			)echo 'selected="selected"'; ?>>Macao                                       	</option>
			<option value="Macedonia"                                   			<?php if($profileDone==1&&$country=="Macedonia"                                   			)echo 'selected="selected"'; ?>>Macedonia                                   	</option>
			<option value="Madagascar"                                  			<?php if($profileDone==1&&$country=="Madagascar"                                  			)echo 'selected="selected"'; ?>>Madagascar                                  	</option>
			<option value="Malawi"                                      			<?php if($profileDone==1&&$country=="Malawi"                                      			)echo 'selected="selected"'; ?>>Malawi                                      	</option>
			<option value="Malaysia"                                    			<?php if($profileDone==1&&$country=="Malaysia"                                    			)echo 'selected="selected"'; ?>>Malaysia                                    	</option>
			<option value="Maldives"                                    			<?php if($profileDone==1&&$country=="Maldives"                                    			)echo 'selected="selected"'; ?>>Maldives                                    	</option>
			<option value="Mali"                                        			<?php if($profileDone==1&&$country=="Mali"                                        			)echo 'selected="selected"'; ?>>Mali                                        	</option>
			<option value="Malta"                                       			<?php if($profileDone==1&&$country=="Malta"                                       			)echo 'selected="selected"'; ?>>Malta                                       	</option>
			<option value="Marshall Islands"                            			<?php if($profileDone==1&&$country=="Marshall Islands"                            			)echo 'selected="selected"'; ?>>Marshall Islands                            	</option>
			<option value="Martinique"                                  			<?php if($profileDone==1&&$country=="Martinique"                                  			)echo 'selected="selected"'; ?>>Martinique                                  	</option>
			<option value="Mauritania"                                  			<?php if($profileDone==1&&$country=="Mauritania"                                  			)echo 'selected="selected"'; ?>>Mauritania                                  	</option>
			<option value="Mauritius"                                   			<?php if($profileDone==1&&$country=="Mauritius"                                   			)echo 'selected="selected"'; ?>>Mauritius                                   	</option>
			<option value="Mayotte"                                     			<?php if($profileDone==1&&$country=="Mayotte"                                     			)echo 'selected="selected"'; ?>>Mayotte                                     	</option>
			<option value="Mexico"                                      			<?php if($profileDone==1&&$country=="Mexico"                                      			)echo 'selected="selected"'; ?>>Mexico                                      	</option>
			<option value="Micronesia"                                  			<?php if($profileDone==1&&$country=="Micronesia"                                  			)echo 'selected="selected"'; ?>>Micronesia                                  	</option>
			<option value="Moldova"                                     			<?php if($profileDone==1&&$country=="Moldova"                                     			)echo 'selected="selected"'; ?>>Moldova                                     	</option>
			<option value="Monaco"                                      			<?php if($profileDone==1&&$country=="Monaco"                                      			)echo 'selected="selected"'; ?>>Monaco                                      	</option>
			<option value="Mongolia"                                    			<?php if($profileDone==1&&$country=="Mongolia"                                    			)echo 'selected="selected"'; ?>>Mongolia                                    	</option>
			<option value="Montenegro"                                  			<?php if($profileDone==1&&$country=="Montenegro"                                  			)echo 'selected="selected"'; ?>>Montenegro                                  	</option>
			<option value="Montserrat"                                  			<?php if($profileDone==1&&$country=="Montserrat"                                  			)echo 'selected="selected"'; ?>>Montserrat                                  	</option>
			<option value="Morocco"                                     			<?php if($profileDone==1&&$country=="Morocco"                                     			)echo 'selected="selected"'; ?>>Morocco                                     	</option>
			<option value="Mozambique"                                  			<?php if($profileDone==1&&$country=="Mozambique"                                  			)echo 'selected="selected"'; ?>>Mozambique                                  	</option>
			<option value="Myanmar"                                     			<?php if($profileDone==1&&$country=="Myanmar"                                     			)echo 'selected="selected"'; ?>>Myanmar                                     	</option>
			<option value="Namibia"                                     			<?php if($profileDone==1&&$country=="Namibia"                                     			)echo 'selected="selected"'; ?>>Namibia                                     	</option>
			<option value="Nauru"                                       			<?php if($profileDone==1&&$country=="Nauru"                                       			)echo 'selected="selected"'; ?>>Nauru                                       	</option>
			<option value="Nepal"                                       			<?php if($profileDone==1&&$country=="Nepal"                                       			)echo 'selected="selected"'; ?>>Nepal                                       	</option>
			<option value="Netherlands Antilles"                        			<?php if($profileDone==1&&$country=="Netherlands Antilles"                        			)echo 'selected="selected"'; ?>>Netherlands Antilles                        	</option>
			<option value="Netherlands"                                 			<?php if($profileDone==1&&$country=="Netherlands"                                 			)echo 'selected="selected"'; ?>>Netherlands                                 	</option>
			<option value="New Caledonia"                               			<?php if($profileDone==1&&$country=="New Caledonia"                               			)echo 'selected="selected"'; ?>>New Caledonia                               	</option>
			<option value="New Zealand"                                 			<?php if($profileDone==1&&$country=="New Zealand"                                 			)echo 'selected="selected"'; ?>>New Zealand                                 	</option>
			<option value="Nicaragua"                                   			<?php if($profileDone==1&&$country=="Nicaragua"                                   			)echo 'selected="selected"'; ?>>Nicaragua                                   	</option>
			<option value="Niger"                                       			<?php if($profileDone==1&&$country=="Niger"                                       			)echo 'selected="selected"'; ?>>Niger                                       	</option>
			<option value="Nigeria"                                     			<?php if($profileDone==1&&$country=="Nigeria"                                     			)echo 'selected="selected"'; ?>>Nigeria                                     	</option>
			<option value="Niue"                                        			<?php if($profileDone==1&&$country=="Niue"                                        			)echo 'selected="selected"'; ?>>Niue                                        	</option>
			<option value="Norfolk Island"                              			<?php if($profileDone==1&&$country=="Norfolk Island"                              			)echo 'selected="selected"'; ?>>Norfolk Island                              	</option>
			<option value="North Korea"                                 			<?php if($profileDone==1&&$country=="North Korea"                                 			)echo 'selected="selected"'; ?>>North Korea                                 	</option>
			<option value="Northern Mariana Islands"                    		    <?php if($profileDone==1&&$country=="Northern Mariana Islands"                    			)echo 'selected="selected"'; ?>>Northern Mariana Islands                    	</option>
			<option value="Norway"                                      			<?php if($profileDone==1&&$country=="Norway"                                      			)echo 'selected="selected"'; ?>>Norway                                      	</option>
			<option value="Oman"                                        			<?php if($profileDone==1&&$country=="Oman"                                        			)echo 'selected="selected"'; ?>>Oman                                        	</option>
			<option value="Pakistan"                                    			<?php if($profileDone==1&&$country=="Pakistan"                                    			)echo 'selected="selected"'; ?>>Pakistan                                    	</option>
			<option value="Palau"                                       			<?php if($profileDone==1&&$country=="Palau"                                       			)echo 'selected="selected"'; ?>>Palau                                       	</option>
			<option value="Palestinian Territory"                       			<?php if($profileDone==1&&$country=="Palestinian Territory"                       			)echo 'selected="selected"'; ?>>Palestinian Territory                       	</option>
			<option value="Panama"                                      			<?php if($profileDone==1&&$country=="Panama"                                      			)echo 'selected="selected"'; ?>>Panama                                      	</option>
			<option value="Papua New Guinea"                            			<?php if($profileDone==1&&$country=="Papua New Guinea"                            			)echo 'selected="selected"'; ?>>Papua New Guinea                            	</option>
			<option value="Paraguay"                                    			<?php if($profileDone==1&&$country=="Paraguay"                                    			)echo 'selected="selected"'; ?>>Paraguay                                    	</option>
			<option value="Peru"                                        			<?php if($profileDone==1&&$country=="Peru"                                        			)echo 'selected="selected"'; ?>>Peru                                        	</option>
			<option value="Philippines"                                 			<?php if($profileDone==1&&$country=="Philippines"                                 			)echo 'selected="selected"'; ?>>Philippines                                 	</option>
			<option value="Pitcairn"                                    			<?php if($profileDone==1&&$country=="Pitcairn"                                    			)echo 'selected="selected"'; ?>>Pitcairn                                    	</option>
			<option value="Poland"                                      			<?php if($profileDone==1&&$country=="Poland"                                      			)echo 'selected="selected"'; ?>>Poland                                      	</option>
			<option value="Portugal"                                    			<?php if($profileDone==1&&$country=="Portugal"                                    			)echo 'selected="selected"'; ?>>Portugal                                    	</option>
			<option value="Puerto Rico"                                 			<?php if($profileDone==1&&$country=="Puerto Rico"                                 			)echo 'selected="selected"'; ?>>Puerto Rico                                 	</option>
			<option value="Qatar"                                       			<?php if($profileDone==1&&$country=="Qatar"                                       			)echo 'selected="selected"'; ?>>Qatar                                       	</option>
			<option value="Republic of the Congo"                       			<?php if($profileDone==1&&$country=="Republic of the Congo"                       			)echo 'selected="selected"'; ?>>Republic of the Congo                       	</option>
			<option value="Reunion"                                     			<?php if($profileDone==1&&$country=="Reunion"                                     			)echo 'selected="selected"'; ?>>Reunion                                     	</option>
			<option value="Romania"                                     			<?php if($profileDone==1&&$country=="Romania"                                     			)echo 'selected="selected"'; ?>>Romania                                     	</option>
			<option value="Russia"                                      			<?php if($profileDone==1&&$country=="Russia"                                      			)echo 'selected="selected"'; ?>>Russia                                      	</option>
			<option value="Rwanda"                                      			<?php if($profileDone==1&&$country=="Rwanda"                                      			)echo 'selected="selected"'; ?>>Rwanda                                      	</option>
			<option value="Saint Barthelemy"                            			<?php if($profileDone==1&&$country=="Saint Barthelemy"                            			)echo 'selected="selected"'; ?>>Saint Barthelemy                            	</option>
			<option value="Saint Helena"                                			<?php if($profileDone==1&&$country=="Saint Helena"                                			)echo 'selected="selected"'; ?>>Saint Helena                                	</option>
			<option value="Saint Kitts and Nevis"                       			<?php if($profileDone==1&&$country=="Saint Kitts and Nevis"                       			)echo 'selected="selected"'; ?>>Saint Kitts and Nevis                       	</option>
			<option value="Saint Lucia"                                 			<?php if($profileDone==1&&$country=="Saint Lucia"                                 			)echo 'selected="selected"'; ?>>Saint Lucia                                 	</option>
			<option value="Saint Martin"                                			<?php if($profileDone==1&&$country=="Saint Martin"                                			)echo 'selected="selected"'; ?>>Saint Martin                                	</option>
			<option value="Saint Pierre and Miquelon"                   		    <?php if($profileDone==1&&$country=="Saint Pierre and Miquelon"                   			)echo 'selected="selected"'; ?>>Saint Pierre and Miquelon                   	</option>
			<option value="Saint Vincent and the Grenadines"           		        <?php if($profileDone==1&&$country=="Saint Vincent and the Grenadines"           			)echo 'selected="selected"'; ?>>Saint Vincent and the Grenadines            	</option>
			<option value="Samoa"                                       			<?php if($profileDone==1&&$country=="Samoa"                                       			)echo 'selected="selected"'; ?>>Samoa                                       	</option>
			<option value="San Marino"                                  			<?php if($profileDone==1&&$country=="San Marino"                                  			)echo 'selected="selected"'; ?>>San Marino                                  	</option>
			<option value="Sao Tome and Principe"                       			<?php if($profileDone==1&&$country=="Sao Tome and Principe"                       			)echo 'selected="selected"'; ?>>Sao Tome and Principe                       	</option>
			<option value="Saudi Arabia"                                			<?php if($profileDone==1&&$country=="Saudi Arabia"                                			)echo 'selected="selected"'; ?>>Saudi Arabia                                	</option>
			<option value="Senegal"                                     			<?php if($profileDone==1&&$country=="Senegal"                                     			)echo 'selected="selected"'; ?>>Senegal                                     	</option>
			<option value="Serbia and Montenegro"                       			<?php if($profileDone==1&&$country=="Serbia and Montenegro"                       			)echo 'selected="selected"'; ?>>Serbia and Montenegro                       	</option>
			<option value="Serbia"                                      			<?php if($profileDone==1&&$country=="Serbia"                                      			)echo 'selected="selected"'; ?>>Serbia                                      	</option>
			<option value="Seychelles"                                  			<?php if($profileDone==1&&$country=="Seychelles"                                  			)echo 'selected="selected"'; ?>>Seychelles                                  	</option>
			<option value="Sierra Leone"                                			<?php if($profileDone==1&&$country=="Sierra Leone"                                			)echo 'selected="selected"'; ?>>Sierra Leone                                	</option>
			<option value="Singapore"                                   			<?php if($profileDone==1&&$country=="Singapore"                                   			)echo 'selected="selected"'; ?>>Singapore                                   	</option>
			<option value="Sint Maarten"                                			<?php if($profileDone==1&&$country=="Sint Maarten"                                			)echo 'selected="selected"'; ?>>Sint Maarten                                	</option>
			<option value="Slovakia"                                    			<?php if($profileDone==1&&$country=="Slovakia"                                    			)echo 'selected="selected"'; ?>>Slovakia                                    	</option>
			<option value="Slovenia"                                    			<?php if($profileDone==1&&$country=="Slovenia"                                    			)echo 'selected="selected"'; ?>>Slovenia                                    	</option>
			<option value="Solomon Islands"                             			<?php if($profileDone==1&&$country=="Solomon Islands"                             			)echo 'selected="selected"'; ?>>Solomon Islands                             	</option>
			<option value="Somalia"                                     			<?php if($profileDone==1&&$country=="Somalia"                                     			)echo 'selected="selected"'; ?>>Somalia                                     	</option>
			<option value="South Africa"                                			<?php if($profileDone==1&&$country=="South Africa"                                			)echo 'selected="selected"'; ?>>South Africa                                	</option>
			<option value="South Georgia and the South Sandwich Islands"		    <?php if($profileDone==1&&$country=="South Georgia and the South Sandwich Islands"			)echo 'selected="selected"'; ?>>South Georgia and the South Sandwich Islands	</option>
			<option value="South Korea"                                 			<?php if($profileDone==1&&$country=="South Korea"                                 			)echo 'selected="selected"'; ?>>South Korea                                 	</option>
			<option value="South Sudan"                                 			<?php if($profileDone==1&&$country=="South Sudan"                                 			)echo 'selected="selected"'; ?>>South Sudan                                 	</option>
			<option value="Spain"                                       			<?php if($profileDone==1&&$country=="Spain"                                       			)echo 'selected="selected"'; ?>>Spain                                       	</option>
			<option value="Sri Lanka"                                   			<?php if($profileDone==1&&$country=="Sri Lanka"                                   			)echo 'selected="selected"'; ?>>Sri Lanka                                   	</option>
			<option value="Sudan"                                       			<?php if($profileDone==1&&$country=="Sudan"                                       			)echo 'selected="selected"'; ?>>Sudan                                       	</option>
			<option value="Suriname"                                    			<?php if($profileDone==1&&$country=="Suriname"                                    			)echo 'selected="selected"'; ?>>Suriname                                    	</option>
			<option value="Svalbard and Jan Mayen"                      			<?php if($profileDone==1&&$country=="Svalbard and Jan Mayen"                      			)echo 'selected="selected"'; ?>>Svalbard and Jan Mayen                      	</option>
			<option value="Swaziland"                                   			<?php if($profileDone==1&&$country=="Swaziland"                                   			)echo 'selected="selected"'; ?>>Swaziland                                   	</option>
			<option value="Sweden"                                      			<?php if($profileDone==1&&$country=="Sweden"                                      			)echo 'selected="selected"'; ?>>Sweden                                      	</option>
			<option value="Switzerland"                                 			<?php if($profileDone==1&&$country=="Switzerland"                                 			)echo 'selected="selected"'; ?>>Switzerland                                 	</option>
			<option value="Syria"                                       			<?php if($profileDone==1&&$country=="Syria"                                       			)echo 'selected="selected"'; ?>>Syria                                       	</option>
			<option value="Taiwan"                                      			<?php if($profileDone==1&&$country=="Taiwan"                                      			)echo 'selected="selected"'; ?>>Taiwan                                      	</option>
			<option value="Tajikistan"                                  			<?php if($profileDone==1&&$country=="Tajikistan"                                  			)echo 'selected="selected"'; ?>>Tajikistan                                  	</option>
			<option value="Tanzania"                                    			<?php if($profileDone==1&&$country=="Tanzania"                                    			)echo 'selected="selected"'; ?>>Tanzania                                    	</option>
			<option value="Thailand"                                    			<?php if($profileDone==1&&$country=="Thailand"                                    			)echo 'selected="selected"'; ?>>Thailand                                    	</option>
			<option value="Togo"                                        			<?php if($profileDone==1&&$country=="Togo"                                        			)echo 'selected="selected"'; ?>>Togo                                        	</option>
			<option value="Tokelau"                                     			<?php if($profileDone==1&&$country=="Tokelau"                                     			)echo 'selected="selected"'; ?>>Tokelau                                     	</option>
			<option value="Tonga"                                       			<?php if($profileDone==1&&$country=="Tonga"                                       			)echo 'selected="selected"'; ?>>Tonga                                       	</option>
			<option value="Trinidad and Tobago"                         			<?php if($profileDone==1&&$country=="Trinidad and Tobago"                         			)echo 'selected="selected"'; ?>>Trinidad and Tobago                         	</option>
			<option value="Tunisia"                                     			<?php if($profileDone==1&&$country=="Tunisia"                                     			)echo 'selected="selected"'; ?>>Tunisia                                     	</option>
			<option value="Turkey"                                      			<?php if($profileDone==1&&$country=="Turkey"                                      			)echo 'selected="selected"'; ?>>Turkey                                      	</option>
			<option value="Turkmenistan"                                			<?php if($profileDone==1&&$country=="Turkmenistan"                                			)echo 'selected="selected"'; ?>>Turkmenistan                                	</option>
			<option value="Turks and Caicos Islands"                    		    <?php if($profileDone==1&&$country=="Turks and Caicos Islands"                    			)echo 'selected="selected"'; ?>>Turks and Caicos Islands                    	</option>
			<option value="Tuvalu"                                      			<?php if($profileDone==1&&$country=="Tuvalu"                                      			)echo 'selected="selected"'; ?>>Tuvalu                                      	</option>
			<option value="U.S. Virgin Islands"                         			<?php if($profileDone==1&&$country=="U.S. Virgin Islands"                         			)echo 'selected="selected"'; ?>>U.S. Virgin Islands                         	</option>
			<option value="Uganda"                                      			<?php if($profileDone==1&&$country=="Uganda"                                      			)echo 'selected="selected"'; ?>>Uganda                                      	</option>
			<option value="Ukraine"                                     			<?php if($profileDone==1&&$country=="Ukraine"                                     			)echo 'selected="selected"'; ?>>Ukraine                                     	</option>
			<option value="United Arab Emirates"                        			<?php if($profileDone==1&&$country=="United Arab Emirates"                        			)echo 'selected="selected"'; ?>>United Arab Emirates                        	</option>
			<option value="United Kingdom"                              			<?php if($profileDone==1&&$country=="United Kingdom"                              			)echo 'selected="selected"'; ?>>United Kingdom                              	</option>
			<option value="United States Minor Outlying Islands"       		        <?php if($profileDone==1&&$country=="United States Minor Outlying Islands"       			)echo 'selected="selected"'; ?>>United States Minor Outlying Islands        	</option>
			<option value="United States"       									<?php if($profileDone==1&&$country=="United States"       									)echo 'selected="selected"'; ?>>United States				        			</option>
			<option value="Uruguay"                                     			<?php if($profileDone==1&&$country=="Uruguay"                                     			)echo 'selected="selected"'; ?>>Uruguay                                     	</option>
			<option value="Uzbekistan"                                  			<?php if($profileDone==1&&$country=="Uzbekistan"                                  			)echo 'selected="selected"'; ?>>Uzbekistan                                  	</option>
			<option value="Vanuatu"                                     			<?php if($profileDone==1&&$country=="Vanuatu"                                     			)echo 'selected="selected"'; ?>>Vanuatu                                     	</option>
			<option value="Vatican"                                     			<?php if($profileDone==1&&$country=="Vatican"                                     			)echo 'selected="selected"'; ?>>Vatican                                     	</option>
			<option value="Venezuela"                                   			<?php if($profileDone==1&&$country=="Venezuela"                                   			)echo 'selected="selected"'; ?>>Venezuela                                   	</option>
			<option value="Vietnam"                                     			<?php if($profileDone==1&&$country=="Vietnam"                                     			)echo 'selected="selected"'; ?>>Vietnam                                     	</option>
			<option value="Wallis and Futuna"                           			<?php if($profileDone==1&&$country=="Wallis and Futuna"                           			)echo 'selected="selected"'; ?>>Wallis and Futuna                           	</option>
			<option value="Western Sahara"                              			<?php if($profileDone==1&&$country=="Western Sahara"                              			)echo 'selected="selected"'; ?>>Western Sahara                              	</option>
			<option value="Yemen"                                       			<?php if($profileDone==1&&$country=="Yemen"                                       			)echo 'selected="selected"'; ?>>Yemen                                       	</option>
			<option value="Zambia"                                      			<?php if($profileDone==1&&$country=="Zambia"                                      			)echo 'selected="selected"'; ?>>Zambia                                      	</option>
			<option value="Zimbabwe"                                    			<?php if($profileDone==1&&$country=="Zimbabwe"                                    			)echo 'selected="selected"'; ?>>Zimbabwe                                    	</option>

	
	